--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/walls/spectre.jpg"

-- Special
background="#0c0a0c"
foreground="#c5cddd"
cursor="#c5cddd"

-- Colors
color0="#0c0a0c"
color1="#625E72"
color2="#C55053"
color3="#67728C"
color4="#92778A"
color5="#7987A4"
color6="#8D95B1"
color7="#c5cddd"
color8="#898f9a"
color9="#625E72"
color10="#C55053"
color11="#67728C"
color12="#92778A"
color13="#7987A4"
color14="#8D95B1"
color15="#c5cddd"
