# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/walls/spectre.jpg'

# Special
background='#0c0a0c'
foreground='#c5cddd'
cursor='#c5cddd'

# Colors
color0='#0c0a0c'
color1='#625E72'
color2='#C55053'
color3='#67728C'
color4='#92778A'
color5='#7987A4'
color6='#8D95B1'
color7='#c5cddd'
color8='#898f9a'
color9='#625E72'
color10='#C55053'
color11='#67728C'
color12='#92778A'
color13='#7987A4'
color14='#8D95B1'
color15='#c5cddd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
