# Shell variables
# Generated by 'wal'
wallpaper='/home/amanre/.config/xfce-wallpapers/windows.jpg'

# Special
background='#0b0332'
foreground='#a6a1c8'
cursor='#a6a1c8'

# Colors
color0='#0b0332'
color1='#980065'
color2='#B10068'
color3='#C5006A'
color4='#0E3887'
color5='#0D4898'
color6='#0B5CAB'
color7='#a6a1c8'
color8='#74708c'
color9='#980065'
color10='#B10068'
color11='#C5006A'
color12='#0E3887'
color13='#0D4898'
color14='#0B5CAB'
color15='#a6a1c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
